### ISSUE TITLE
Omit deleted/private videos?

### ISSUE THREAD

**Issue by arcnmx** [arcnmx/MPD#9]
Playlists can include deleted or private videos, and those aren't of much use to anyone?

Filtering by title (which seems to be the only indicator youtube gives, short of making additional requests to check) sounds like a bad idea though, so maybe don't do this.

**Comment by Rio6** [comment]
Yeah it looks like the only thing youtube-dl give is "[Deleted video]" in flat playlist mode. Matching the exact string is definitely not ideal since that'll only work on Youtube.

Using full playlist mode with --ignore-errors flag set automatically skips unavailable videos, but is super slow.

What if we include the deleted videos anyway, and let it errors out at the input plugin side? They are technically part of the playlist after all, much like how a m3u file can contain deleted files.

**Comment by arcnmx** [comment]
Yeah there's probably no other reasonable approach to take here. The youtube-dl extractor can be modified to omit them if it's really a problem for anyone.
